name: debug

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "test Tag"
        required: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node.js modules
        run: npm install

      - name: Install vsce
        run: npm i -g vsce

      - name: VSCE Packge
        run: vsce package

  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node.js modules
        run: npm install

      - name: Install vsce
        run: npm i -g vsce

      - name: VSCE Packge
        run: |
          vsce package
          APK=$(find ./ -name '*vscode-leetcode-problem-rating*.vsix')
      - uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: ${{ env.APK }}

  darwin:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node.js modules
        run: npm install

      - name: Install vsce
        run: npm i -g vsce

      - name: VSCE Packge
        run: vsce package
